// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: proto/pass-gen.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PasswordGeneratorClient is the client API for PasswordGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasswordGeneratorClient interface {
	Generate(ctx context.Context, in *PassParam, opts ...grpc.CallOption) (*GenResult, error)
}

type passwordGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewPasswordGeneratorClient(cc grpc.ClientConnInterface) PasswordGeneratorClient {
	return &passwordGeneratorClient{cc}
}

func (c *passwordGeneratorClient) Generate(ctx context.Context, in *PassParam, opts ...grpc.CallOption) (*GenResult, error) {
	out := new(GenResult)
	err := c.cc.Invoke(ctx, "/passwordGenerator.PasswordGenerator/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordGeneratorServer is the server API for PasswordGenerator service.
// All implementations must embed UnimplementedPasswordGeneratorServer
// for forward compatibility
type PasswordGeneratorServer interface {
	Generate(context.Context, *PassParam) (*GenResult, error)
	mustEmbedUnimplementedPasswordGeneratorServer()
}

// UnimplementedPasswordGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedPasswordGeneratorServer struct {
}

func (UnimplementedPasswordGeneratorServer) Generate(context.Context, *PassParam) (*GenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedPasswordGeneratorServer) mustEmbedUnimplementedPasswordGeneratorServer() {}

// UnsafePasswordGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasswordGeneratorServer will
// result in compilation errors.
type UnsafePasswordGeneratorServer interface {
	mustEmbedUnimplementedPasswordGeneratorServer()
}

func RegisterPasswordGeneratorServer(s grpc.ServiceRegistrar, srv PasswordGeneratorServer) {
	s.RegisterService(&PasswordGenerator_ServiceDesc, srv)
}

func _PasswordGenerator_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordGeneratorServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passwordGenerator.PasswordGenerator/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordGeneratorServer).Generate(ctx, req.(*PassParam))
	}
	return interceptor(ctx, in, info, handler)
}

// PasswordGenerator_ServiceDesc is the grpc.ServiceDesc for PasswordGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PasswordGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "passwordGenerator.PasswordGenerator",
	HandlerType: (*PasswordGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _PasswordGenerator_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pass-gen.proto",
}
